# 项目相关配置
tienchin:
  # 名称
  name: RuoYi
  # 版本
  version: 0.0.1
  # 版权年份
  copyrightYear: 2022
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/tienchin/uploadPath，Linux配置 /home/tienchin/uploadPath）
  profile: D:/tienchin/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math
  contract:
    file: /Users/sang/Documents/contract_file

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8081
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    org.emilia: debug
    org.springframework: warn

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles: 
    active: druid
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  5MB
       # 设置总上传的文件大小
       max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: 192.168.15.151
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 1
    # 密码
    password: 123
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
# Spring Boot 2.x + Spring Security 5.x 配置
  security:
    # 1. 禁用默认的用户认证（避免自动生成随机密码，且不拦截未认证请求）
    user:
      name: ignore  # 占位符，实际已禁用认证，此配置无意义但需填写（2.x 版本兼容）
      password: ignore
    # 2. 配置 Security 过滤器链：全局放行所有路径
    filter-chain:
      # 匹配所有请求路径（/** 表示所有层级的路径）
      pattern: /**
      # 对匹配的路径禁用认证（即不拦截）
      security: none
    # 3. 关闭 CSRF 保护（若不关闭，POST/PUT/DELETE 等请求仍可能被拦截）
    csrf:
      enabled: false
    # 4. 关闭会话管理（避免因会话失效导致的拦截）
    session:
      management:
        session-creation-policy: stateless  # 无状态模式，不依赖会话
# token配置
token:
    # 令牌自定义标识
    header: Authorization
    # 令牌密钥
    secret: abcdefghijklmnopqrstuvwxyz
    # 令牌有效期（默认30分钟）
    expireTime: 30
  
# MyBatis配置
mybatis:
#    # 搜索指定包别名
#    typeAliasesPackage: org.emilia.**.mapper
#    # 配置mapper的扫描，找到所有的mapper.xml映射文件
#    mapperLocations: classpath*:mapper/**/*Mapper.xml
#    # 加载全局的配置文件
#    configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper: 
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql 

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# 防止XSS攻击
xss: 
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

